export const songsList = [
  {
    title: "Les Trementinaires",
    artist: "Pilar Pelegri Terrado",
    //  flag: '333',
    artwork: require("../images/foto-Trementinaire.webp"),
    url: require("../audios/Trementinairescatalan.mp3"),
    id: "1",
  },
  {
    title: "Las Trementinaires",
    artist: "Pilar Pelegri Terrado",
    //  flag: '777',
    artwork: require("../images/foto-Trementinaire.webp"),
    url: require("../audios/cast_Trementinaires.mp3"),
    id: "2",
  },
  {
    title: "L'arribada del tren a Mataró",
    artist: "Medistoris",
    // flag: '333',
    artwork: require("../images/Mataro_foto.webp"),
    url: require("../audios/tren_catalan.mp3"),
    id: "3",
  },
  {
    title: "La llegada del tren a Mataró",
    artist: "Medistoris",
    // flag: '777',
    artwork: require("../images/Mataro_foto.webp"),
    url: require("../audios/trencastellano.mp3"),
    id: "4",
  },
  {
    title: "El Timbaler del Bruc",
    artist: "Medistoris",
    // flag: '333',
    artwork: require("../images/timbaler4.webp"),
    url: require("../audios/Catalan_Timbaler.mp3"),
    id: "5",
  },
  {
    title: "El Tamborilero del Bruc",
    artist: "Medistoris",
    // flag: '777',
    artwork: require("../images/timbaler4.webp"),
    url: require("../audios/Cast_Timbaler.mp3"),
    id: "6",
  },
  {
    title: "Manresa el misteri de la llum",
    artist: "Alba Subirà Fernández",
    // flag: '333',
    artwork: require("../images/Manresa_foto_new.webp"),
    url: require("../audios/Manresa.mp3"),
    id: "7",
  },
  {
    title: "La Llegenda de Sant Jordi",
    artist: "Octavi Pujades",
    // flag: '333',
    artwork: require("../images/jordi_new.webp"),
    url: require("../audios/santjordicatalan.mp3"),
    id: "8",
  },

  {
    title: "La Leyenda de Sant Jordi",
    artist: "Octavi Pujades",
    // flag: '777',
    artwork: require("../images/222.webp"),
    url: require("../audios/newSanjordi_cast.mp3"),
    id: "9",
  },
  {
    title: "El Cant dels ocells",
    artist: "Flàvia Camacho Martínez",
    artwork: require("../images/ocells.webp"),
    url: require("../audios/Cant_dels_ocells.mp3"),
    id: "10",
  },
  {
    title: "El noi de la mare",
    artist: "Cristina Ferrero Celaya",
    artwork: require("../images/Noide.webp"),
    url: require("../audios/El_noi_de_la_mare.mp3"),
    id: "11",
  },
  {
    title: "La lluna la pruna",
    artist: "Cristina Ferrero Celaya",
    artwork: require("../images/Lallunalapruna.webp"),
    url: require("../audios/La_lluna_la_pruna.mp3"),
    id: "12",
  },
  {
    title: "Mesos de l’any",
    artist: "Assumpta Rojas Gibert",
    artwork: require("../images/Dite2_foto.webp"),
    url: require("../audios/Dites2.mp3"),
    id: "13",
  },
  {
    title: "A l’estiu Tota cuca viu",
    artist: "Assumpta Rojas Gibert",
    artwork: require("../images/Dite3_foto.webp"),
    url: require("../audios/Dites3.mp3"),
    id: "14",
  },
  {
    title: "Qui dia passa, any empeny",
    artist: "Assumpta Rojas Gibert",
    artwork: require("../images/Dites1_foto.webp"),
    url: require("../audios/Dites1.mp3"),
    id: "15",
  },
];

export const sliderSongs = [
  // {
  //   title: 'Manresa el misteri de la llum',
  //   artist: 'Alba Subirà Fernández',
  //   artwork: require('../images/Manresa_foto.jpg'),
  //   url: require('../audios/newManresa.mp3'),
  //   id: '7',
  // },

  {
    title: "El Cant dels ocells",
    artist: "Flàvia Camacho Martínez",
    artwork: require("../images/ocells.webp"),
    url: require("../audios/Cant_dels_ocells.mp3"),
    id: "8",
  },
  {
    title: "L'arribada del tren a Mataró",
    artist: "KPimarketing.es",
    flag: "333",
    artwork: require("../images/Mataro_foto.webp"),
    url: require("../audios/trencastellano.mp3"),
    id: "3",
  },
  {
    title: "Medistoris",
    artist: "Aplicació",
    artwork: require("../images/ocells.webp"),
    url: require("../audios/Cant_dels_ocells.mp3"),
    id: "14",
  },
];
